# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20161107_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookpage',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookpage',
            name='page_number',
            field=models.PositiveSmallIntegerField(default=1, unique=True),
        ),
    ]
