# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20161112_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookpage',
            name='page_number',
            field=models.PositiveSmallIntegerField(default=0, unique=True),
        ),
    ]
