# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20161112_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookpage',
            name='title',
            field=models.CharField(default='', max_length=13),
        ),
    ]
